### EDA1
This is a notebook for formatting and working with the first 10000 tweets. I built this to just get the pathlibs right and attempt to process tweets using pandas.
I think this can get us where we want and will serve as the base code for the process_tweets.py file later. I created ukraine_processed using this notebook. This is a bad practice but was expedient as our dataset is still in its infant stage.

In [1]:
import pandas as pd
import urllib.parse as urlparse
from pathlib import Path

In [2]:
path = Path.cwd()
path_root = path.parent
data_Dir = path_root.joinpath('data')
file_Path = data_Dir.joinpath("nagorno.csv")
print(file_Path)
tweets = pd.read_csv(file_Path) # This is a dataframe of actors on twitter and their information
tweets.head(10)

c:\Users\Matt\Documents\MISM-BIDA\84740_TPSUML\CMU_TwiVer_Project\data\nagorno.csv

C:\Users\Matt\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (35,37,38,39,62,63,64) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,conversation_id,referenced_tweets.replied_to.id,referenced_tweets.retweeted.id,referenced_tweets.quoted.id,edit_history_tweet_ids,edit_controls.edits_remaining,edit_controls.editable_until,edit_controls.is_edit_eligible,author_id,...,geo.geo.type,geo.id,geo.name,geo.place_id,geo.place_type,matching_rules,__twarc.retrieved_at,__twarc.url,__twarc.version,Unnamed: 78
0,1309643847870406656,1309643847870406656,NaN,1.309504e+18,NaN,"[""1309643847870406656""]",5,2020-09-26T00:29:59.000Z,True,2188272130,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
1,1309643846746243072,1309643846746243072,NaN,NaN,NaN,"[""1309643846746243072""]",5,2020-09-26T00:29:59.000Z,True,592068889,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
2,1309643846020526082,1309643846020526082,NaN,1.309124e+18,NaN,"[""1309643846020526082""]",5,2020-09-26T00:29:59.000Z,True,440826628,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
3,1309643845521387522,1309643845521387522,NaN,1.309456e+18,NaN,"[""1309643845521387522""]",5,2020-09-26T00:29:59.000Z,True,15213963,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
4,1309643844883972097,1309643844883972097,NaN,1.309585e+18,NaN,"[""1309643844883972097""]",5,2020-09-26T00:29:59.000Z,True,1291035141201166337,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
5,1309643844695330816,1309643844695330816,NaN,1.309377e+18,NaN,"[""1309643844695330816""]",5,2020-09-26T00:29:59.000Z,True,1291078589681741828,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
6,1309643844674187265,1309642824309063681,1.309643e+18,NaN,NaN,"[""1309643844674187265""]",5,2020-09-26T00:29:59.000Z,True,932964325957894145,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
7,1309643844481429505,1309643844481429505,NaN,1.309332e+18,NaN,"[""1309643844481429505""]",5,2020-09-26T00:29:59.000Z,True,925846715013398534,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
8,1309643843231510529,1309643843231510529,NaN,1.309599e+18,NaN,"[""1309643843231510529""]",5,2020-09-26T00:29:58.000Z,True,1180264405600210944,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
9,1309643843105624064,1309631828660158464,1.309632e+18,NaN,NaN,"[""1309643843105624064""]",5,2020-09-26T00:29:58.000Z,True,117986908,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-20T15:41:33+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN

In [3]:

tweets_processed = tweets.loc[:, ['id', 'text']]
tweets_processed.head(10)

                    id                                               text
0  1309643847870406656  It’s too bad Trump didn’t have decades of sexu...
1  1309643846746243072                  $80 for the charlo fight 🤦‍♂️🤦‍♂️
2  1309643846020526082  I honestly was ready to fight 😂😂. Need to work...
3  1309643845521387522  Good to see @Matt_KeanMP is against the Brandy...
4  1309643844883972097  Conor McGregor is in "serious talks" to fight ...
5  1309643844695330816  The United States didn’t survive a civil war, ...
6  1309643844674187265                       @sharuna413 (๑•̀o•́๑)۶ FIGHT
7  1309643844481429505  On The Road With Al and Ivy: A Homeless Litera...
8  1309643843231510529  The EPA illegally destroyed records, deceived ...
9  1309643843105624064          @misshonoredxx Ma’am, please destroy me🙏🏻

In [4]:
out_path = data_Dir.joinpath("nagorno_processed.csv")
tweets_processed.to_csv(out_path, header=False, index=False)

In [7]:
#This doesnt work. I think its how I pulled the tweets. Still I think we can work with what I got.

tweets_group_by = tweets.loc[:, ['id','conversation_id', 'text']]
tweets_two =tweets_group_by.groupby("conversation_id", group_keys=True).apply(lambda x:x)
tweets_two.head(10)

,id,conversation_id,text
0,1496273598436331528,1496233391989170181,@GraceOnFootball Without going all false equiv...
1,1496273598251782144,1496273598251782144,Trump sides with Putin over the United States ...
2,1496273598100684807,1496273598100684807,(1) Riddle me this... If Biden Inc are so worr...
3,1496273597719056386,1496273597719056386,@Denis_Buchholz @Cinderoak This is when Putin'...
4,1496273597480017925,1496273597480017925,"Let's see how many agree that about the ""geniu..."
5,1496273597433880579,1496273597433880579,In 2014 Obama sanction Putin oligarch mate Tim...
6,1496273597266116611,1496273597266116611,"Anti-sanctions accounts have graduated to, ""sa..."
7,1496273597257719811,1496273597257719811,The Putin we saw yesterday quite clearly won't...
8,1496273597173805060,1496273498796343299,Bisschen mehr Schröder nach Moskau schicken un...
9,1496273597085720577,1496273597085720577,What if Trump backs Putin over Biden? Will tha...