### EDA1
This is a notebook for formatting and working with the first 10000 tweets. I built this to just get the pathlibs right and attempt to process tweets using pandas.
I think this can get us where we want and will serve as the base code for the process_tweets.py file later. I created ukraine_processed using this notebook. This is a bad practice but was expedient as our dataset is still in its infant stage.

In [2]:
import pandas as pd
import urllib.parse as urlparse
from pathlib import Path

In [3]:
path = Path.cwd()
path_root = path.parent
data_Dir = path_root.joinpath('data')
file_Path = data_Dir.joinpath("ukraine.csv")
print(file_Path)
tweets = pd.read_csv(file_Path) # This is a dataframe of actors on twitter and their information
tweets.head(10)

c:\Users\Matt\Documents\MISM-BIDA\84740_TPSUML\CMU_TwiVer_Project\data\ukraine.csv

C:\Users\Matt\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (27,35,37,38,39) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,conversation_id,referenced_tweets.replied_to.id,referenced_tweets.retweeted.id,referenced_tweets.quoted.id,edit_history_tweet_ids,edit_controls.edits_remaining,edit_controls.editable_until,edit_controls.is_edit_eligible,author_id,...,geo.geo.type,geo.id,geo.name,geo.place_id,geo.place_type,matching_rules,__twarc.retrieved_at,__twarc.url,__twarc.version,Unnamed: 78
0,1496273598436331528,1496233391989170181,1.496233e+18,NaN,NaN,"[""1496273598436331528""]",5,2022-02-23T00:29:59.000Z,True,1450473310123401231,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
1,1496273598251782144,1496273598251782144,NaN,1.496273e+18,NaN,"[""1496273598251782144""]",5,2022-02-23T00:29:59.000Z,True,19926586,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
2,1496273598100684807,1496273598100684807,NaN,1.496215e+18,NaN,"[""1496273598100684807""]",5,2022-02-23T00:29:59.000Z,True,2925286221,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
3,1496273597719056386,1496273597719056386,NaN,1.495942e+18,NaN,"[""1496273597719056386""]",5,2022-02-23T00:29:59.000Z,True,1065601942838235137,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
4,1496273597480017925,1496273597480017925,NaN,1.496264e+18,NaN,"[""1496273597480017925""]",5,2022-02-23T00:29:59.000Z,True,710882693,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
5,1496273597433880579,1496273597433880579,NaN,NaN,NaN,"[""1496273597433880579""]",5,2022-02-23T00:29:59.000Z,True,322889483,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
6,1496273597266116611,1496273597266116611,NaN,NaN,1.496142e+18,"[""1496273597266116611""]",5,2022-02-23T00:29:59.000Z,True,465193714,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
7,1496273597257719811,1496273597257719811,NaN,1.496215e+18,NaN,"[""1496273597257719811""]",5,2022-02-23T00:29:59.000Z,True,3362792968,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
8,1496273597173805060,1496273498796343299,1.496274e+18,NaN,NaN,"[""1496273597173805060""]",5,2022-02-23T00:29:59.000Z,True,995280714303180800,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN
9,1496273597085720577,1496273597085720577,NaN,1.496254e+18,NaN,"[""1496273597085720577""]",5,2022-02-23T00:29:59.000Z,True,803949092443299840,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-19T10:07:45+00:00,https://api.twitter.com/2/tweets/search/all?ex...,2.12.0,NaN

In [4]:

tweets_processed = tweets.loc[:, ['id', 'text']]
tweets_processed.head(10)

                    id                                               text
0  1496273598436331528  @GraceOnFootball Without going all false equiv...
1  1496273598251782144  Trump sides with Putin over the United States ...
2  1496273598100684807  (1) Riddle me this... If Biden Inc are so worr...
3  1496273597719056386  @Denis_Buchholz @Cinderoak This is when Putin'...
4  1496273597480017925  Let's see how many agree that about the "geniu...
5  1496273597433880579  In 2014 Obama sanction Putin oligarch mate Tim...
6  1496273597266116611  Anti-sanctions accounts have graduated to, "sa...
7  1496273597257719811  The Putin we saw yesterday quite clearly won't...
8  1496273597173805060  Bisschen mehr Schröder nach Moskau schicken un...
9  1496273597085720577  What if Trump backs Putin over Biden? Will tha...

In [23]:
out_path = data_Dir.joinpath("ukraine_processed.csv")
tweets_processed.to_csv(out_path, header=False, index=False)

In [7]:
#This doesnt work. I think its how I pulled the tweets. Still I think we can work with what I got.

tweets_group_by = tweets.loc[:, ['id','conversation_id', 'text']]
tweets_two =tweets_group_by.groupby("conversation_id", group_keys=True).apply(lambda x:x)
tweets_two.head(10)

,id,conversation_id,text
0,1496273598436331528,1496233391989170181,@GraceOnFootball Without going all false equiv...
1,1496273598251782144,1496273598251782144,Trump sides with Putin over the United States ...
2,1496273598100684807,1496273598100684807,(1) Riddle me this... If Biden Inc are so worr...
3,1496273597719056386,1496273597719056386,@Denis_Buchholz @Cinderoak This is when Putin'...
4,1496273597480017925,1496273597480017925,"Let's see how many agree that about the ""geniu..."
5,1496273597433880579,1496273597433880579,In 2014 Obama sanction Putin oligarch mate Tim...
6,1496273597266116611,1496273597266116611,"Anti-sanctions accounts have graduated to, ""sa..."
7,1496273597257719811,1496273597257719811,The Putin we saw yesterday quite clearly won't...
8,1496273597173805060,1496273498796343299,Bisschen mehr Schröder nach Moskau schicken un...
9,1496273597085720577,1496273597085720577,What if Trump backs Putin over Biden? Will tha...